display_name: Тикетик
package_name: ticketik
version: "0.8.5"
maintainer:
  name: Ticketik Team
  email: support@ticketik.local
co_authors:
  - Ticketik Team
priority: optional
section: x11
installed_size: 68000
essential: false
icon: linux/runner/app_icon.ico
keywords:
  - Тикетик
  - техподдержка
  - заявки
generic_name: Система заявок
description: |
  Тикетик – быстрая отправка заявок в техподдержку
  Приложение для автоматической отправки заявок с определением устройства
categories:
  - Utility
startup_notify: true
desktop_file: linux/runner/ticketik.desktop
dependencies:
  - gtk3
  - libappindicator
